import {
  BaseDeclarativeTool,
  BaseToolInvocation,
  Kind,
  type ToolInvocation,
  type ToolResult,
} from './tools.js';
import { ToolErrorType } from './tool-error.js';
import type { Config } from '../config/config.js';
import { ToolNames, ToolDisplayNames } from './tool-names.js';
import * as fs from 'fs/promises';
import * as path from 'path';

/**
 * OpenSim simulation-asset generator (Phase 3 stub).
 *
 * Unlike OpenGame, where every simulation needs sprites / audio /
 * tilesets generated by an external image model, OpenSim simulations
 * mostly draw themselves from Three.js geometry — Pendulum / Beaker /
 * GridSurface are r3f components, not generated images. The only
 * remaining "asset" need is *external scientific data*: parameter
 * tables (NIST, PubChem), pre-computed initial conditions, lookup
 * tables from a paper, or domain datasets to compare against.
 *
 * Phase 3 ships this as a stub that:
 *   1. Validates the request shape so the LLM gets a meaningful tool
 *      surface (the agent can plan around it).
 *   2. Writes the requested assets to \`public/assets/\` as plain JSON
 *      stubs the caller can fill in by hand or via a Phase-5 follow-up.
 *
 * Phase 4 (ode_system rollout) decides whether to flesh out:
 *   - HTTP fetchers for known science APIs (Wolfram Alpha, NIST WebBook,
 *     PubChem REST), or
 *   - LLM-driven synthetic-data generation for parameter tables, or
 *   - Both.
 *
 * Until then, ODE simulations should leave Protocol Section 1 empty.
 */

export type SimulationAssetType =
  | 'dataset'
  | 'parameter_table'
  | 'initial_condition'
  | 'lookup';

export interface SimulationAssetRequest {
  type: SimulationAssetType;
  /** Stable key the simulation code will reference, e.g. "co2_concentrations". */
  key: string;
  /** Free-text description; future fetchers parse this. */
  description: string;
  /** Optional URL or DOI hint for external data. */
  source?: string;
}

export interface GenerateSimulationAssetsParams {
  output_dir_name?: string;
  assets: SimulationAssetRequest[];
}

class GenerateSimulationAssetsInvocation extends BaseToolInvocation<
  GenerateSimulationAssetsParams,
  ToolResult
> {
  constructor(private config: Config, params: GenerateSimulationAssetsParams) {
    super(params);
  }

  getDescription(): string {
    return `Generate ${this.params.assets.length} simulation asset stub(s).`;
  }

  async execute(_signal: AbortSignal): Promise<ToolResult> {
    try {
      const outputDir = path.join(
        this.config.getProjectRoot(),
        this.params.output_dir_name || 'public/assets',
      );
      await fs.mkdir(outputDir, { recursive: true });

      const written: string[] = [];
      for (const asset of this.params.assets) {
        const fileName = `${asset.key}.json`;
        const fullPath = path.join(outputDir, fileName);
        const stub = {
          key: asset.key,
          type: asset.type,
          description: asset.description,
          source: asset.source ?? null,
          status: 'stub',
          notice:
            'Phase-3 stub — fill in real values manually or wire a fetcher in a later phase.',
          values: null,
        };
        await fs.writeFile(fullPath, JSON.stringify(stub, null, 2), 'utf-8');
        written.push(fileName);
      }

      // Append/refresh an asset-pack index so the simulator runtime can
      // discover stubs without re-listing the directory.
      const indexPath = path.join(outputDir, 'asset-pack.json');
      let pack: Record<string, { files: SimulationAssetRequest[] }> = {};
      try {
        pack = JSON.parse(await fs.readFile(indexPath, 'utf-8'));
      } catch {
        pack = {};
      }
      pack['datasets'] = pack['datasets'] || { files: [] };
      pack['datasets'].files = this.params.assets;
      await fs.writeFile(indexPath, JSON.stringify(pack, null, 2), 'utf-8');

      const list = written.map((f) => `  - ${f}`).join('\n');
      return {
        llmContent: `Wrote ${written.length} simulation asset stub(s) to ${outputDir}:\n${list}\n\nNOTE: each is a JSON STUB with no real data — fill manually or extend this tool in a later phase.`,
        returnDisplay: `**Simulation Assets (stubs)**\n\nWrote ${written.length} stub file(s) to \`${this.params.output_dir_name || 'public/assets'}/\`. Each contains \`{ "status": "stub", "values": null }\` and must be filled in before the simulation reads from it.`,
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      return {
        llmContent: `Error writing simulation asset stubs: ${message}`,
        returnDisplay: `**Asset Generation Failed**\n\nError: ${message}`,
        error: { message, type: ToolErrorType.EXECUTION_FAILED },
      };
    }
  }
}

export class GenerateSimulationAssetsTool extends BaseDeclarativeTool<
  GenerateSimulationAssetsParams,
  ToolResult
> {
  static readonly Name: string = ToolNames.GENERATE_SIMULATION_ASSETS;

  constructor(private config: Config) {
    super(
      GenerateSimulationAssetsTool.Name,
      ToolDisplayNames.GENERATE_SIMULATION_ASSETS,
      `Phase-3 stub for OpenSim's simulation-asset pipeline. Writes JSON placeholders for datasets / parameter tables / initial conditions / lookups under public/assets/. Most ODE simulations need NOTHING here and should not call this tool. Calling this tool does NOT yet fetch real external data — it just creates stub files the developer (or a future fetcher) fills in.`,
      Kind.Other,
      {
        type: 'object',
        properties: {
          output_dir_name: {
            type: 'string',
            description: 'Output directory relative to project root. Default "public/assets".',
          },
          assets: {
            type: 'array',
            description:
              'Asset requests to stub out. Each gets a JSON file at <output>/<key>.json.',
            items: {
              type: 'object',
              properties: {
                type: {
                  type: 'string',
                  enum: [
                    'dataset',
                    'parameter_table',
                    'initial_condition',
                    'lookup',
                  ],
                  description:
                    'dataset = time-series or table of measurements; parameter_table = constants by name; initial_condition = state vector to seed a solver; lookup = function table evaluated at runtime.',
                },
                key: {
                  type: 'string',
                  description:
                    'Stable identifier the simulation code references, e.g. "co2_history".',
                },
                description: {
                  type: 'string',
                  description:
                    'Free-form description. Future fetchers may parse it.',
                },
                source: {
                  type: 'string',
                  description: 'Optional source URL / DOI / paper reference.',
                },
              },
              required: ['type', 'key', 'description'],
            },
          },
        },
        required: ['assets'],
      },
      false,
      true,
    );
  }

  protected override validateToolParamValues(
    params: GenerateSimulationAssetsParams,
  ): string | null {
    if (!Array.isArray(params.assets) || params.assets.length === 0) {
      return '`assets` must be a non-empty array. If the simulation needs no external data, do not call this tool.';
    }
    return null;
  }

  protected createInvocation(
    params: GenerateSimulationAssetsParams,
  ): ToolInvocation<GenerateSimulationAssetsParams, ToolResult> {
    return new GenerateSimulationAssetsInvocation(this.config, params);
  }
}
